### ISSUE TITLE
Gemfile.lock files causes failure

### ISSUE THREAD

**Issue by Reedyuk** [bitrise-io/steps-cocoapods-install#10]
Hi,
I had a gemfile.lock in my root of my project, this caused the cocoapods install to fail, i assume its because you look for any .lock file in the step.
After i removed the gemfile.lock then it worked fine.

**Comment by viktorbenei** [comment]
Without the log hard to say, but yes, the step searches for Gemfile(.lock) in the repo and if you have one it expects that you defined the CocoaPods version you want to use in that.

What was/is in your `Gemfile`?

**Comment by Reedyuk** [comment]
[Archive.zip](https://github.com/bitrise-io/steps-cocoapods-install/files/320497/Archive.zip)

**Comment by Reedyuk** [comment]
+------------------------------------------------------------------------------+
| (4) cocoapods-install@1.4.2                                                  |
+------------------------------------------------------------------------------+
| id: cocoapods-install                                                        |
| version: 1.4.2                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| time: 2016-06-17T13:29:08+01:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |
Configs:
  * source_root_path: /Users/reeda/Documents/xcode/nutmeg-ios
  * podfile_path: 
  * [deprecated!] is_update_cocoapods: false
  * install_cocoapods_version: 1.0.1

-> $ cd /Users/reeda/Documents/xcode/nutmeg-ios

update cocoapods to: 1.0.1

-> $ gem uninstall --all --executables cocoapods

You have requested to uninstall the gem:
	cocoapods-1.0.1

jazzy-0.6.3 depends on cocoapods (~> 1.0)
If you remove this gem, these dependencies will not be met.
Continue with Uninstall? [yN]  N
ERROR:  While executing gem ... (Gem::DependencyRemovalException)
    Uninstallation aborted due to dependent gem(s)
 [!] Failed!
 (i) No cleanup function defined - exiting now
|                                                                              |
+----+--------------------------------------------------------------+----------+
| 🚫  | cocoapods-install@1.4.2 (exit code: 1)                       | 316 sec  |
+----+--------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-io/steps-cocoapods-install/issues  |
| Source: https://github.com/bitrise-io/steps-cocoapods-install                |
+----+--------------------------------------------------------------+----------+

**Comment by viktorbenei** [comment]
Is this the same issue?

**Comment by Reedyuk** [comment]
yes, when i removed the .lock file, it worked fine.

**Comment by viktorbenei** [comment]
Thanks for reporting!

**Comment by viktorbenei** [comment]
We're working on the revision of this step, the new version will fix this issue too.

**Comment by Reedyuk** [comment]
No worries, i might be reporting some issues in the next week. Also i might make some custom steps too.

**Comment by viktorbenei** [comment]
Sounds awesome! Let us know if we can help with anything! 😉

**Comment by godrei** [comment]
Hi @Reedyuk ,
we released a [new version](https://github.com/bitrise-io/steps-cocoapods-install/releases/tag/1.5.2) of the step , can you please take a look on it? it is available in steplib, please let me know, how does it work.

**Comment by Reedyuk** [comment]
Yes confirmed as working. Thanks.

**Comment by viktorbenei** [comment]
Thanks for reporting! 😊
