### ISSUE TITLE
Failing to connect to GitHub

### ISSUE THREAD

**Issue by hanishabsigh** [bitrise-io/steps-cocoapods-install#21]
Not sure if this step is to blame or the environment. I'm using CocoaPods 1.0.1 on Xcode 8.

`fatal: unable to access 'https://github.com/mixpanel/mixpanel-iphone.git/': Failed to connect to github.com port 443: Operation timed out`

**Comment by viktorbenei** [comment]
This is not related to this step, this is a network error. We saw this to happen a couple of times, still investigating what causes it.

I'll close this ticket here, as it's not related to this step, but if you'd have this issue again please feel free to create an issue in the main issue tracker: https://github.com/bitrise-io/bitrise.io
