### ISSUE TITLE
Cocoapod install fails

### ISSUE THREAD

**Issue by laeroah** [bitrise-io/steps-cocoapods-install#22]
The compile failed with:
```
+---+---------------------------------------------------------------+----------+
| x | cocoapods-install@1.5.7 (exit code: 1)                        | 129 sec  |
```
Project is a swift iOS app using cocoapod.
Please advice. Thanks!

**Comment by viktorbenei** [comment]
Please include the rest of the step's log

**Comment by Punith1234** [comment]
same here..

**Comment by viktorbenei** [comment]
Please include the full step log, without that it's impossible to say anything useful

**Comment by Punith1234** [comment]
`+------------------------------------------------------------------------------+
|                               bitrise summary                                |
+---+---------------------------------------------------------------+----------+
|   | title                                                         | time (s) |
+---+---------------------------------------------------------------+----------+
| ✓ | activate-ssh-key@3.1.1                                        | 2.30 sec |
+---+---------------------------------------------------------------+----------+
| ✓ | git-clone@3.4.0                                               | 13 sec   |
+---+---------------------------------------------------------------+----------+
| ✓ | Do anything with Script step                                  | 3.32 sec |
+---+---------------------------------------------------------------+----------+
| ✓ | certificate-and-profile-installer@1.7.0                       | 6.27 sec |
+---+---------------------------------------------------------------+----------+
| x | cocoapods-install@1.5.7 (exit code: 1)                        | 154 sec  |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-io/steps-cocoapods-install/issues  |
| Source: https://github.com/bitrise-io/steps-cocoapods-install                |
+---+---------------------------------------------------------------+----------+
| - | recreate-user-schemes@0.9.4                                   | 1.45 sec |
+---+---------------------------------------------------------------+----------+
| ✓ | deploy-to-bitrise-io@1.2.5                                    | 5.99 sec |
+---+---------------------------------------------------------------+----------+
| Total runtime: 186 sec                                                       |
+------------------------------------------------------------------------------+

INFO[05:09:56]                                              
INFO[05:09:56] Submitting anonymized usage information...   
INFO[05:09:56] For more information visit:                  
INFO[05:09:56] https://github.com/bitrise-core/bitrise-plugins-analytics/blob/master/README.md 
Command failed: exit status 1
`

**Comment by viktorbenei** [comment]
@Punith1234 please include the __CocoaPods Install__ step's log, which looks like this:

```
+------------------------------------------------------------------------------+
| (3) cocoapods-install                                                        |
+------------------------------------------------------------------------------+
| id: cocoapods-install                                                        |
| version: 1.5.7                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2016-11-02T04:10:51-07:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |

Configs:
  * source_root_path: /Users/vagrant/git
  * podfile_path: 
  * system_cocoapods_version: 1.1.1
  * verbose: true
...
|                                                                              |
+---+---------------------------------------------------------------+----------+
| ✓ | cocoapods-install                                             | 19 sec   |
+---+---------------------------------------------------------------+----------+
```

**Comment by laeroah** [comment]
Hey, I think I've found out the issue. I had a development pod with path:
../../../[folder name]
I had to change it to 
../../ 
It's working now. However, the old way did work on Travis-CI. I think we can close this issue. Thank you guys so much for the help.

**Comment by viktorbenei** [comment]
Makes sense @laeroah - depending on the configuration, this step changes to the `Gemfile`'s directory for the `pod install`, in which case relative paths have to be relative to that dir
