### ISSUE TITLE
Call "bundle install" instead of "pod install"?

### ISSUE THREAD

**Issue by bwdowikowski** [bitrise-io/steps-cocoapods-install#27]
So new 1.60 version changed a bit how bitrise figuring out what version of cocoapods is needed.
Is there a way to call "bundle install"  instead of "pod install" ?

Because at this momen I have scripts that have required gems. Previously this step did download them because it did calls `  bundle "install" "--jobs" "20" "--retry" "5" `, but now it is `pod "_1.1.1_" "install" "--no-repo-update" "--verbose"`
Is there a way to override this setting?

**Comment by viktorbenei** [comment]
Can you please ask this at https://discuss.bitrise.io/t/cocoapods-install-step-v1-6-0/208 @bwdowikowski ? That could help others to see the notes & insights, and to add theirs.

**Comment by bwdowikowski** [comment]
Sure thing

**Comment by viktorbenei** [comment]
Thank you! :)
