### ISSUE TITLE
Cocoapod install step failed

### ISSUE THREAD

**Issue by tonifirnandes** [bitrise-io/steps-cocoapods-install#33]
Team, please have a look into this error detail:

![image](https://user-images.githubusercontent.com/3122029/39037827-e1a80406-44ab-11e8-8be8-c682e40f00f1.png)

this our podfile looks like : 
![image](https://user-images.githubusercontent.com/3122029/39042119-4aa45614-44b4-11e8-8b0f-f2ac32c2e44b.png)

Thanks for your kindly support.

**Comment by viktorbenei** [comment]
Hi @tonifirnandes ,

Can you please replace the "smart quotes" around `target 'HelpsterCompany'` with regular single or double quotes? That will fix this issue.

I'll create an internal card to improve the error message.

**Comment by viktorbenei** [comment]
Ohh and of course if you'd have any questions just let us know! :)

**Comment by tonifirnandes** [comment]
Thank you very much team, just noticed there are some inappropriate smart quotes in our pod file. Anyway, we have another issue, would you like to help us resolved it thanks.

[helpster-bitrise-error-log.log](https://github.com/bitrise-io/steps-cocoapods-install/files/1931669/helpster-bitrise-error-log.log)

**Comment by viktorbenei** [comment]
Glad to hear you managed to solve that issue @tonifirnandes ! :)

> Anyway, we have another issue, would you like to help us resolved it thanks.

It seems that's not related to this issue, can you please create a new one? To make it easier for others to find the right one when they are searching for a solution for the same issue :)

**Comment by tonifirnandes** [comment]
Oke thank you very much team. i'll create new one.
