### ISSUE TITLE
Error installing some dependecies (ex: EVWDropDownNotification (0.2.0))

### ISSUE THREAD

**Issue by tonifirnandes** [bitrise-io/steps-cocoapods-install#34]
Hello team,

After resolving smart quotes problem, we got another issue on cocoa pod step install : 

![image](https://user-images.githubusercontent.com/3122029/39046109-3977f0f2-44bf-11e8-8d7b-5ce434eeab3e.png)

Here, the error log detail:
[helpster-bitrise-error-log.log](https://github.com/bitrise-io/steps-cocoapods-install/files/1931729/helpster-bitrise-error-log.log)

Thank you very much for the support team.

**Comment by tonifirnandes** [comment]
To summary the error point maybe : 
-> Installing EVWDropDownNotification (0.2.0)
 > Git download
 > Git download
     $ /usr/local/bin/git clone https://github.com/cre8it/EVWDropDownNotification.git /var/folders/lb/8n5bn9k975qgw662jpqdy7mm0000gn/T/d20180420-1647-1rfu67i --template= --single-branch --depth 1 --branch 0.2.0
     Cloning into '/var/folders/lb/8n5bn9k975qgw662jpqdy7mm0000gn/T/d20180420-1647-1rfu67i'...
     fatal: could not read Username for 'https://github.com': Device not configured
[!] Error installing EVWDropDownNotification
[!] /usr/local/bin/git clone https://github.com/cre8it/EVWDropDownNotification.git /var/folders/lb/8n5bn9k975qgw662jpqdy7mm0000gn/T/d20180420-1647-1rfu67i --template= --single-branch --depth 1 --branch 0.2.0
Cloning into '/var/folders/lb/8n5bn9k975qgw662jpqdy7mm0000gn/T/d20180420-1647-1rfu67i'...
fatal: could not read Username for 'https://github.com': Device not configured
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.3.1/lib/cocoapods/downloader.rb:142:in `rescue in execute_command'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.3.1/lib/cocoapods/downloader.rb:140:in `execute_command'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-downloader-1.2.0/lib/cocoapods-downloader/base.rb:154:in `block in executable'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-downloader-1.2.0/lib/cocoapods-downloader/git.rb:79:in `block in clone'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.3.1/lib/cocoapods/downloader.rb:173:in `block in ui_sub_action'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.3.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.3.1/lib/cocoapods/downloader.rb:172:in `ui_sub_action'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-downloader-1.2.0/lib/cocoapods-downloader/git.rb:77:in `clone'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-downloader-1.2.0/lib/cocoapods-downloader/git.rb:45:in `download!'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-downloader-1.2.0/lib/cocoapods-downloader/base.rb:82:in `block in download'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.3.1/lib/cocoapods/downloader.rb:157:in `block in ui_action'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.3.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.3.1/lib/cocoapods/downloader.rb:156:in `ui_action'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-downloader-1.2.0/lib/cocoapods-downloader/base.rb:80:in `download'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.3.1/lib/cocoapods/downloader.rb:108:in `download_source'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.3.1/lib/cocoapods/downloader.rb:75:in `download_request'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.3.1/lib/cocoapods/downloader/cache.rb:171:in `download'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.3.1/lib/cocoapods/downloader/cache.rb:154:in `block in uncached_pod'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.3.1/lib/cocoapods/downloader/cache.rb:181:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.3.1/lib/cocoapods/downloader/cache.rb:181:in `in_tmpdir'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.3.1/lib/cocoapods/downloader/cache.rb:153:in `uncached_pod'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.3.1/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.3.1/lib/cocoapods/downloader.rb:42:in `download'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/pod_source_installer.rb:120:in `download_source'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/pod_source_installer.rb:60:in `install!'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:364:in `install_source_of_pod'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:329:in `block (2 levels) in install_pod_sources'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.3.1/lib/cocoapods/user_interface.rb:85:in `titled_section'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:328:in `block in install_pod_sources'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:320:in `each'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:320:in `install_pod_sources'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:163:in `block in download_dependencies'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.3.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:161:in `download_dependencies'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:117:in `install!'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.3.1/lib/cocoapods/command/install.rb:41:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.3.1/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.3.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
Command failed, error: exit status 1
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | cocoapods-install@1.7.2 (exit code: 1)                        | 490 sec  |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-io/steps-cocoapods-install/issues  |
| Source: https://github.com/bitrise-io/steps-cocoapods-install                |
+---+---------------------------------------------------------------+----------+

**Comment by viktorbenei** [comment]
Hi @tonifirnandes ,

The issue seems to be:

```
fatal: could not read Username for 'https://github.com': Device not configured
```

This means that you use a private CocoaPods pod repo hosted on github.com - am I right?
If that's the case, then it's failing because you did not grant access to bitrise to access that private github repo.

In general there are two solutions:

1. Configure your git URLs to use SSH keys (git@... url instead of https://... git clone url) - related docs: https://devcenter.bitrise.io/faq/adding-projects-with-submodules/
1. Or, probably easier in your case, authenticate https git clone requests with an API token. For GitHub you can use the **Authenticate with GitHub OAuth** step. Simply follow the guide of the step to generate an appropriate GitHub Personal Access Token - you can see this in the description of the **Personal Access Token** input of the step on the web UI, or you can find it in the step's spec yml too: https://github.com/bitrise-steplib/steps-authenticate-with-github-oauth/blob/master/step.yml#L32
    * Simply add this **Authenticate with GitHub OAuth** step **before** the CocoaPods one, to authenticate requests to GitHub using the Access Token you specify for all subsequent steps
    * Then follow the Personal Access Token generation guide as I mentioned above
    * Once you have that GitHub Personal Access Token simply specify it as the value of this input (or preferably do it in Secrets and specify the secret as the value, but it's up to you)

If you'd have any questions just let us know! :)

**Comment by tonifirnandes** [comment]
Well explained team, anyway i tried to do some basic pod install instruction on my local machine without any auth github setup, then the lib can be installed correctly. You can see in this picture below:

![image](https://user-images.githubusercontent.com/3122029/39047983-191930c6-44c6-11e8-85f0-cb4423e67478.png)

Actually that lib from open source project where we don't know about special auth/access to the repo and i believe the auth isnot need to access that, wehere we can get From the library readme instruction/documentation : https://github.com/carabina/EVWDropDownNotification

Thanks.

**Comment by tonifirnandes** [comment]
Anyway i think, the system spot into wrong repo, because when we access it directly resulted not found : 
![image](https://user-images.githubusercontent.com/3122029/39049130-5f279130-44ca-11e8-9366-30da2eb1f0e1.png)

**Comment by viktorbenei** [comment]
Good catch! Does it work if you change the URL in your `Podfile`?

**Comment by tonifirnandes** [comment]
Yes, thanks for helping us about that.
