### ISSUE TITLE
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

### ISSUE THREAD

**Issue by mieszko4** [bitrise-io/steps-cocoapods-install#35]
Just recently I started getting the following error:
It seems like `pod install` is not executed so `Pods/Manifest.lock` is not there
```
▸ Check Dependencies
    ignoring recursive header expansion for path '/**'
▸ Running script '[CP] Check Pods Manifest.lock'
❌  error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
Last lines of the Xcode's build log:
    /bin/sh -c /Users/vagrant/Library/Developer/Xcode/DerivedData/IvyspaceStudent-hfxlppfptdptgnedaidofsyfquaw/Build/Intermediates.noindex/ArchiveIntermediates/IvyspaceStudent/IntermediateBuildFilesPath/IvyspaceStudent.build/Release-iphoneos/IvyspaceStudent.build/Script-0BA7863857CBD338E1A17F34.sh
diff: /Users/vagrant/git/apps/ivyspace-student/ios/Pods/Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
** ARCHIVE FAILED **
```

Could you give me some tips to resolve this issue please?

**Comment by BirmacherAkos** [comment]
Hi!

Can you please send the URL of the build? :)

----

It is possible that the "Run CocoaPods install" step is not running before the "Xcode Archive & Export" step?

I think the best idea is to put the "Run CocoaPods install" step right after the "Git Clone Repository" step.

**Comment by mieszko4** [comment]
Hi!

The url of the build is https://www.bitrise.io/build/7cb1934a9b9bd934

The more detailed error is:
`ArgumentError - Malformed version number string`

And I figured out that the problem started happening when stable stack was updated by bitirise - I think updating cocoapods in the stable stack caused the problem.

**Temporary solution:** I've just figured out that when I choose `Previous Hybrid (Xamarin, Ionic, ...) on macOS, includes Visual Studio for Mac, Stable channel` stack the builds are working again.

I will try to update cocoapods locally now and see if it will work with current stable stack.

**Comment by viktorbenei** [comment]
@mieszko4 please upgrade your CocoaPods version on your Mac and then run a `pod install` or `pod update` with it, so that it updates the required cocoapods version in the `Podfile.lock` and of course commit the change.

This is required because older cocoapods versions have this issue (the `Malformed version number string` one) with newer Ruby versions. The latest CocoaPods (1.5.3) fixes it and can work with newer ruby versions.

You can find the official cocoapods issue report & thread at: https://github.com/CocoaPods/CocoaPods/issues/7765#issuecomment-391950260

**Comment by mieszko4** [comment]
After installing newest pod (`sudo gem install cocoapods`), running `pod install` and pushing the changes bitrise is working again with Stable stack.

Thanx guys for your help! I will close this issue now.

**Comment by viktorbenei** [comment]
Glad to hear - thanks for reporting @mieszko4 ! :)
