### ISSUE TITLE
Does not install Pod pointing to repo

### ISSUE THREAD

**Issue by tomhartnett** [bitrise-io/steps-cocoapods-install#36]
The cocoapods-install step doesn't seem to handle pods that are being pulled directly from a repo in the Podfile.  In my Podfile, I have a pod like this:

`pod 'SomePodName', :git => 'https://somepodname-repo/the-pod-sdk.git'`

This installs fine and builds locally in Xcode.  Cocoapods.org website shows this method of adding a pod on their site:  https://guides.cocoapods.org/using/the-podfile.html (see "_From a podspec in the root of a library repo_" section).

But my bitrise build doesn't install the pod, and then the build fails because this pod wasn't installed.

I'm using version 1.7.2 of cocoapods-install step.

**Comment by BirmacherAkos** [comment]
Hi!

Could you try to specify the source of the private podspec repo instead of using the `:git =>` version?

```
source 'https://github.com/CocoaPods/Specs.git'
source 'https://somepodname-repo/the-pod-sdk.git'

# There are no targets called "Shows" in any Xcode projects
abstract_target 'Shows' do
  pod 'ShowsKit'
  pod 'Fabric'

  # Has its own copy of ShowsKit + ShowWebAuth
  target 'ShowsiOS' do
    pod 'ShowWebAuth'
  end

  # Has its own copy of ShowsKit + ShowTVAuth
  target 'ShowsTV' do
    pod 'ShowTVAuth'
  end
end
```

**Comment by tomhartnett** [comment]
I tried that and it still doesn't work.

**Comment by trapacska** [comment]
Please copy paste your build url here. So we can have a closer look.

**Comment by trapacska** [comment]
Also, is it public git url, or it is your self/hosted or using with SSH?

**Comment by tomhartnett** [comment]
It's public.  There are no SSH keys involved, and I had other developers
test that they could clone the repo to their computers.

I've actually decided to just add this framework as an embedded binary
(instead of pod) and have moved on.  I consider the issue closed from my
perspective.

Thanks,
Tom

**Comment by trapacska** [comment]
All right, thanks for the feedback.

Feel free to ping us again if you encounter any issues with the step.
