### ISSUE TITLE
Suggestion: Fast, no sync pod installs

### ISSUE THREAD

**Issue by scosman** [bitrise-io/steps-cocoapods-install#5]
This step is very slow, and requires syncing a lot of data from cocoapods.

The suggestions in the "Optimize your build times" article include adding your xcworkspace and Pods directory to git. http://devcenter.bitrise.io/docs/optimize-your-build-times . Syncing the Pods folder is a good idea and recommended by cocoapods. However, adding xcworkspace to git isn't usually a good idea, as changes there are auto generated from the Podfile and make for lots of ugly diffs.

Suggestion: If the Pods directory is present, but the xcworkspace is missing, use `pod --no-repo-update install` instead of `pod install` for a faster install (it takes ~5s vs ~200s). I use the script below, for a huge speedup.

<pre>
#!/bin/bash

echo
echo "Starting cocoapod quick install. Will generate xcworkspace, but expects Pods directory to be checked into git."
echo

pod --no-repo-update install

if [ $? -ne 0 ]; then
  echo
  echo "Install failed - spec are likely out of date."
  echo
  echo "Updating specs..."
  pod setup
  echo "Done updating specs. Retrying install"
  echo
  pod --no-repo-update install
fi

if [ $? -ne 0 ]; then
  echo "WARNING: Pod quick install failed! Consider moving back to Bitrise standard cocoapods installer"
  exit 1 
fi
</pre>

**Comment by viktorbenei** [comment]
This is a really good idea! I'm not sure whether this should be automatic (auto detect the Pods folder) or an option instead, but either way would be a great addition.

I'll add this to our internal task list for a review, to see which solution would be better.

**Comment by scosman** [comment]
The pods command is pretty good at returning error status codes as well. You could even just try the `--no-repo-update` version, and fallback to a full install on failure.

**Comment by viktorbenei** [comment]
That's also a good idea. We're not really a fan of "magical" / automatic behaviour, as that's usually way more complicated to debug when something goes wrong. But using the error of `--no-repo-update` might be a viable "automatic" solution.

**Comment by godrei** [comment]
@scosman We are still discussing your suggestion.

What do you mean by:
`However, adding xcworkspace to git isn't usually a good idea, as changes there are auto generated from the Podfile and make for lots of ugly diffs.` ?

We believe that the best (from a CI/build reproducibility point of view) is to push the Pods folder and also the xcworkspace into the repository, becouse in this case no CocoaPods operations are needed.
This (including the workspace file in the repository) means that it doesn't even matter anymore whether CocoaPods is installed or not on the build environment (​*or what version of CocoaPods is installed*​ - CocoaPods 1.0.0 is already in beta and will introduce breaking changes), your build will still work.

That said, as we do provide a CocoaPods Step, your suggested optimization might still be a good improvement, even if our recommendation would be to include the workspace file too.

On the other hand, if you do include the Pods folder but not the workspace file, then you can just drop in a one-liner Script, similar to what you do, as you no longer really need this Step with it’s additional complexity.

We’re still discussing this with our team, feel free to add any comment which can help us decide!

**Comment by scosman** [comment]
I honestly can't figure out where I got that "best practice". I found a few places that say it was in Github's .gitignore template for Xcode, but that long longer seems to be the case.

**Comment by viktorbenei** [comment]
It's not a bad practice (to not to include the workspace, only the Pods dir), but from a reliability/stability point of view, if you include both the Pods and the workspace dirs in your repository, it's simply better (no dependency to CocoaPods at all, it doesn't even have to be installed on the build server).

We'll definitely talk more about this with our team, and your comments are very much welcome!

**Comment by viktorbenei** [comment]
Implemented in [v1.2.0](https://github.com/bitrise-io/steps-cocoapods-install/releases/tag/1.2.0) - let us know if we missed something!

We will close this ticket, but feel free to add notes here, or to create a new issue! And of course, thank you for the suggestion & details! ;)

**Comment by scosman** [comment]
awesome, build cache looks great!
