### ISSUE TITLE
Step never fails after `Analyzing dependencies` timeout [Business critical]

### ISSUE THREAD

**Issue by Ariandr** [bitrise-io/steps-cocoapods-install#81]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 2.2.0
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? SPORADIC
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? NOT APPLICABLE

### Issue description

If the `Analyzing dependencies` goes into timeout, the step doesn't fail and the build never stops. It happened only once for me, but I imagine if the app was on the Credits system and they ran out because of non-stopping build, it would have caused a business issue (money waste).

### Bitrise info

- Build URL: https://app.bitrise.io/build/1938e4c1-44d7-4c38-9a9e-78a2bce40d5d#?tab=log
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: NO
- Log: 
Check selected Ruby is installed
Ruby 2.6.5 is installed
Installing cocoapods
Checking cocoapods 1.11.2 gem
Installed
cocoapods version:
$ pod "_1.11.2_" "--version"
1.11.2
Installing Pods
$ pod "_1.11.2_" "install" "--no-repo-update"
Analyzing dependencies
timeout after 5400 seconds

<details>
  <pre>
Installing Pods
$ pod "_1.11.2_" "install" "--no-repo-update"
Analyzing dependencies
timeout after 5400 seconds
  </pre>
</details>

### Steps to reproduce

The issue cannot be reliably reproduced because the timeout happens rarely. But in case it happens, the build should fail immediately.
<img width="753" alt="Screenshot at Nov 09 16-12-53" src="https://user-images.githubusercontent.com/13591333/140942689-d910ad27-3839-4c46-81a8-3544a15763c4.png">
![image](https://user-images.githubusercontent.com/13591333/140942628-94f1550a-9422-41ef-954b-c034af0b5362.png)
<img width="1120" alt="Screenshot at Nov 09 16-13-42" src="https://user-images.githubusercontent.com/13591333/140942695-c60c5ae7-9b4e-41d6-9ac2-baec88d39050.png">

**Comment by Roland-Bak** [comment]
Hello there @Ariandr 👋

Can you let me know if this issue still persists on the new Xcode 13.1 stack?
If it does, could you please enable Support Access for your app so we can compare builds and try to pinpoint the possible reason why this happens? 🙂

**Comment by Ariandr** [comment]
Hi @Roland-Bak 

`Can you let me know if this issue still persists on the new Xcode 13.1 stack?`
It cannot be reproduced in 99% of cases, so it's impossible to tell. But since it depends on Cocoapods only and this step, it will happen on any Xcode version stack.

It's clearly the issue with the lack of handling of Cocoapods `Analyzing dependencies` timeout.

**Comment by Ariandr** [comment]
The issue must be checked.

**Comment by Roland-Bak** [comment]
Hello there @Ariandr 👋

I wanted to let you know that we are currently looking into the possibility of builds hanging at various parts of the workflow, and this issue seems to be one of those.
The investigation is on the way, and although it has prerequisites that need to be in place in order to progress, as soon as there is a progress, we'll let you know.

I also wanted to mention that in case someone is on a credit based plan and has a timeout issue, we will refund the credits that were spent on a hanged build so that they can use it towards better ends.

Hope this helps! 🙂
